[".vim/pack/plugins/start/vim-surround"]
  type = "git-repo"
  url = "https://github.com/tpope/vim-surround"
  refreshPeriod = "168h"

[".vim/pack/plugins/start/vim-repeat"]
  type = "git-repo"
  url = "https://github.com/tpope/vim-repeat"
  refreshPeriod = "168h"

[".vim/pack/plugins/start/vim-commentary"]
  type = "git-repo"
  url = "https://github.com/tpope/vim-commentary"
  refreshPeriod = "168h"

[".vim/pack/plugins/start/vim-sensible"]
  type = "git-repo"
  url = "https://github.com/tpope/vim-sensible"
  refreshPeriod = "168h"

[".vim/pack/plugins/start/vim-vinegar"]
  type = "git-repo"
  url = "https://github.com/tpope/vim-vinegar"
  refreshPeriod = "168h"

[".vim/pack/plugins/start/vim-jsx-typescript"]
  type = "git-repo"
  url = "https://github.com/peitalin/vim-jsx-typescript"
  refreshPeriod = "168h"

[".vim/pack/plugins/start/vim-sneak"]
  type = "git-repo"
  url = "https://github.com/justinmk/vim-sneak"
  refreshPeriod = "168h"

[".vim/pack/plugins/start/vim-unimpaired"]
  type = "git-repo"
  url = "https://github.com/tpope/vim-unimpaired"
  refreshPeriod = "168h"
