# Special color mode so we can have italics
set -g default-terminal 'tmux-256color'

# Do not override default prefix, instead add another one
set -g prefix C-a

# Vim-like behavior
setw -g mode-keys vi

# Vim-like key bindings for pane navigation
unbind h
bind h select-pane -L
unbind j
bind j select-pane -D
unbind k
bind k select-pane -U
unbind l # normally used for last-window
bind l select-pane -R

# Pane resizing
unbind Left
bind -r Left resize-pane -L 5
unbind Right
bind -r Right resize-pane -R 5
unbind Down
bind -r Down resize-pane -D 5
unbind Up
bind -r Up resize-pane -U 5

# Intuitive window-splitting keys.
bind | split-window -h
bind - split-window -v

# Set history limit to maximum value allowed
set -g history-limit 262144

# Don't wait for an escape sequence after seeing C-a.
set -s escape-time 0

# Start window and pane numbering at 1, (0 is too hard to reach).
set -g base-index 1
set -g pane-base-index 1

# Automatically renumber window numbers on closing a pane
set -g renumber-windows on

# Status bar
set -g status-bg 'colour236'
set -g status-fg 'colour245'

# Custom status bar (based on lightline colors)
setw -g window-status-format '#[fg=colour236,bg=colour236]#[default] #W #[fg=colour236,bg=colour236]'
setw -g window-status-current-format '#[fg=colour236,bg=colour240]#[fg=colour231,bg=colour240] #[bold]#W #[fg=colour240,bg=colour236]'
set -g status-left '#[fg=white,bg=green,bold] #S #[fg=colour148,bg=colour236]'
set -g status-right '#[fg=colour252,bg=colour236]#[fg=colour241,bg=colour252] %H:%M | %A, %B %d, %Y '

bind-key -T copy-mode-vi 'v' send-keys -X begin-selection
bind-key -T copy-mode-vi 'y' send-keys -X copy-pipe "reattach-to-user-namespace pbcopy"
