#!/bin/bash
# set ft=sh

DOTFILES="$HOME/dotfiles"
VS_CODE="$HOME/Library/Application Support/Code/User"

echo "Updating Homebrew..."

brew update &> /dev/null

# Setup npm credentials if needed
if [ ! -f $HOME/.npmrc ]; then
  echo "Adding npm credentials"
  npm adduser
fi

echo "Updating Vim plugins..."

vim +PluginUpdate +PluginUpgrade +qall &> /dev/null

echo "Updating VS Code settings..."

mv $DOTFILES/vscode/* $VS_CODE/

echo "Everything was setup!"
